name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile.vlmcsd --tag needforspeed/vlmcsd:$(date +%s)
        docker build . --file Dockerfile.adguardhome --tag needforspeed/adguardhome:$(date +%s)
